version: "3.9"
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123pass123word123
      MYSQL_DATABASE: app
      MYSQL_USER: credsec
      MYSQL_PASSWORD: 123credsec123
      TIMEZONE: Europe/Copenhagen
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - credsec_network
    hostname: mariadb
    restart: on-failure
    
  web:
    build: .
    working_dir: /code
    command: 
      - /bin/bash
      - -c
      - |
        ./runserver.prod.sh
    volumes:
      - .:/code
    ports:
      - "35729:35729"
    networks:
      - credsec_network
    depends_on:
      - mariadb
    restart: on-failure
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/code/static
    ports:
      - 80:80
      - 30000:30000
    networks:
      - credsec_network
    depends_on:
      - django
    restart: on-failure
networks:
  credsec_network:
