version: "3.9"
services:
  django:
    build: .
    command: 
      - /bin/bash
      - -c
      - |
        ./runserver.sh
    volumes:
      - .:/code
    networks:
      - credsec_network
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: "!!!credsecpasswordisgood!!!"
      MYSQL_DATABASE: app
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - credsec_network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - credsec_network
    depends_on:
      - django
    restart: on-failure
networks:
  credsec_network:
    name: credsec
volumes:
  mariadb_data:
