version: "3.9"
services:
  django:
    build: .
    command: 
      - /bin/bash
      - -c
      - |
        ./runserver.sh
    volumes:
      - .:/code
    networks:
      - credsec_network
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123pass123word123
      MYSQL_DATABASE: app
      MYSQL_USER: credsec
      MYSQL_PASSWORD: 123credsec123
      TIMEZONE: "Europe/Copenhagen"
    ports:
      - "3306:3306"
    expose:
      - 3306
    networks:
      - credsec_network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - credsec_network
    depends_on:
      - django
    restart: on-failure
networks:
  credsec_network:
